apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: flyte
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/lyft/flyte
  shortDescription: >-
  description: |+2
      kubectl-flyte is an command line tool that can be used as an extension to kubectl.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/lyft/flytepropeller/releases/download/{{ .TagName }}/kubectl-flyte_{{ .TagName }}_darwin_x86_64.tar.gz" .TagName | indent 6}}
      files:
        - from: kubectl-flyte
          to: ./flyte
        - from: LICENSE
          to: .
      bin: flyte
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/lyft/flytepropeller/releases/download/{{ .TagName }}/kubectl-flyte_{{ .TagName }}_linux_x86_64.tar.gz" .TagName | indent 6}}
      files:
        - from: kubectl-flyte
          to: ./flyte
        - from: LICENSE
          to: .
      bin: flyte
