name: Master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
  push-github-end2end:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp//tmp/docker-images
          key: /tmp/docker-images-${{ hashFiles('Dockerfile') }}

      - run: docker load -i /tmp//tmp/docker-images/snapshot-builder.tar || true
        if: steps.cache-docker.outputs.cache-hit == 'true'      
      - run: |
          docker build -t lyft/flytepropeller:${{ github.sha }} . --target builder --cache-from=flytepropeller-cache
          docker build -t lyft/flytepropeller:${{ github.sha }} .

      - run: docker tag lyft/flytepropeller:${{ github.sha }} flytepropeller-cache && mkdir -p /tmp//tmp/docker-images && docker save flytepropeller-cache -o /tmp//tmp/docker-images/snapshot.tar && ls -lh /tmp//tmp/docker-images || true
        if: always() && steps.cache-docker.outputs.cache-hit != 'true'

      - uses: engineerd/setup-kind@v0.4.0
      - name: End2End
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          PROPELLER=lyft/flytepropeller:${{ github.sha }} make end2end_execute
  push-dockerhub:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Push Docker Image to Dockerhub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          image_name: ${{ secrets.DOCKERHUB_IMAGE_NAME }}
          image_tag: latest,${{ github.sha }},${{ needs.bump-version.outputs.version }}
          push_git_tag: true
          build_extra_args: "--compress=true"
  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
