name: Pull Request

on:
  pull_request

jobs:
  build-and-end2end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"

      - name: End2End
        run: |
          docker build -t lyft/flytepropeller/flytepropeller:${{ github.sha }} .
          PROPELLER=lyft/flytepropeller/flytepropeller:${{ github.sha }} make end2end_execute

  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
