name: Pull Request

on:
  pull_request

jobs:
  build-and-end2end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: lyft/flytepropeller
          image_tag: latest,${{ github.sha }},${{ needs.bump-version.outputs.version }}
          push_git_tag: false
          registry: docker.pkg.github.com
          build_extra_args: "--compress=true"
          push_image_and_stages : false
      - uses: engineerd/setup-kind@v0.4.0
      - name: End2End
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          PROPELLER=lyft/flytepropeller:${{ github.sha }} make end2end_execute

  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
