name: Pull Request

on:
  pull_request

jobs:
  build-and-end2end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: End2End
        run:
          - make e2e-setup
          - kubectl cluster-info
          - kubectl get pods -n kube-system
          - echo "current-context:" $(kubectl config current-context)
          - echo "environment-kubeconfig:" ${KUBECONFIG}
          - PROPELLER=lyft/flytepropeller/flytepropeller:${{ github.sha }} make end2end_execute
  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
