name: Pull Request

on:
  pull_request

jobs:
  build-and-end2end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"
      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-save
          key: docker-save-${{ hashFiles('Dockerfile') }}
      - run: |
          docker load -i /tmp/docker-save/snapshot.tar || true
          docker build -t lyft/flytepropeller:${{ github.sha }} . --cache-from=flytepropeller-cache
        if: steps.cache-docker.outputs.cache-hit == 'true'
      - run: docker tag lyft/flytepropeller:${{ github.sha }} flytepropeller-cache && mkdir -p /tmp/docker-save && docker save flytepropeller-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
        if: always() && steps.cache-docker.outputs.cache-hit != 'true'
      - uses: engineerd/setup-kind@v0.4.0
      - name: End2End
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          PROPELLER=lyft/flytepropeller:${{ github.sha }} make end2end_execute

  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
